// This file is generated by ttrpc-compiler 0.6.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct AgentServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl AgentServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        AgentServiceClient {
            client: client,
        }
    }

    pub async fn create_container(&self, ctx: ttrpc::context::Context, req: &super::agent::CreateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "CreateContainer", cres);
    }

    pub async fn start_container(&self, ctx: ttrpc::context::Context, req: &super::agent::StartContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "StartContainer", cres);
    }

    pub async fn remove_container(&self, ctx: ttrpc::context::Context, req: &super::agent::RemoveContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "RemoveContainer", cres);
    }

    pub async fn exec_process(&self, ctx: ttrpc::context::Context, req: &super::agent::ExecProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ExecProcess", cres);
    }

    pub async fn signal_process(&self, ctx: ttrpc::context::Context, req: &super::agent::SignalProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "SignalProcess", cres);
    }

    pub async fn wait_process(&self, ctx: ttrpc::context::Context, req: &super::agent::WaitProcessRequest) -> ::ttrpc::Result<super::agent::WaitProcessResponse> {
        let mut cres = super::agent::WaitProcessResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "WaitProcess", cres);
    }

    pub async fn update_container(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "UpdateContainer", cres);
    }

    pub async fn update_ephemeral_mounts(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateEphemeralMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "UpdateEphemeralMounts", cres);
    }

    pub async fn stats_container(&self, ctx: ttrpc::context::Context, req: &super::agent::StatsContainerRequest) -> ::ttrpc::Result<super::agent::StatsContainerResponse> {
        let mut cres = super::agent::StatsContainerResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "StatsContainer", cres);
    }

    pub async fn pause_container(&self, ctx: ttrpc::context::Context, req: &super::agent::PauseContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "PauseContainer", cres);
    }

    pub async fn resume_container(&self, ctx: ttrpc::context::Context, req: &super::agent::ResumeContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ResumeContainer", cres);
    }

    pub async fn remove_stale_virtiofs_share_mounts(&self, ctx: ttrpc::context::Context, req: &super::agent::RemoveStaleVirtiofsShareMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "RemoveStaleVirtiofsShareMounts", cres);
    }

    pub async fn write_stdin(&self, ctx: ttrpc::context::Context, req: &super::agent::WriteStreamRequest) -> ::ttrpc::Result<super::agent::WriteStreamResponse> {
        let mut cres = super::agent::WriteStreamResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "WriteStdin", cres);
    }

    pub async fn read_stdout(&self, ctx: ttrpc::context::Context, req: &super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        let mut cres = super::agent::ReadStreamResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ReadStdout", cres);
    }

    pub async fn read_stderr(&self, ctx: ttrpc::context::Context, req: &super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        let mut cres = super::agent::ReadStreamResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ReadStderr", cres);
    }

    pub async fn close_stdin(&self, ctx: ttrpc::context::Context, req: &super::agent::CloseStdinRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "CloseStdin", cres);
    }

    pub async fn tty_win_resize(&self, ctx: ttrpc::context::Context, req: &super::agent::TtyWinResizeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "TtyWinResize", cres);
    }

    pub async fn update_interface(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateInterfaceRequest) -> ::ttrpc::Result<super::types::Interface> {
        let mut cres = super::types::Interface::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "UpdateInterface", cres);
    }

    pub async fn update_routes(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        let mut cres = super::agent::Routes::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "UpdateRoutes", cres);
    }

    pub async fn list_interfaces(&self, ctx: ttrpc::context::Context, req: &super::agent::ListInterfacesRequest) -> ::ttrpc::Result<super::agent::Interfaces> {
        let mut cres = super::agent::Interfaces::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ListInterfaces", cres);
    }

    pub async fn list_routes(&self, ctx: ttrpc::context::Context, req: &super::agent::ListRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        let mut cres = super::agent::Routes::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ListRoutes", cres);
    }

    pub async fn add_arp_neighbors(&self, ctx: ttrpc::context::Context, req: &super::agent::AddARPNeighborsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "AddARPNeighbors", cres);
    }

    pub async fn get_ip_tables(&self, ctx: ttrpc::context::Context, req: &super::agent::GetIPTablesRequest) -> ::ttrpc::Result<super::agent::GetIPTablesResponse> {
        let mut cres = super::agent::GetIPTablesResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "GetIPTables", cres);
    }

    pub async fn set_ip_tables(&self, ctx: ttrpc::context::Context, req: &super::agent::SetIPTablesRequest) -> ::ttrpc::Result<super::agent::SetIPTablesResponse> {
        let mut cres = super::agent::SetIPTablesResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "SetIPTables", cres);
    }

    pub async fn get_metrics(&self, ctx: ttrpc::context::Context, req: &super::agent::GetMetricsRequest) -> ::ttrpc::Result<super::agent::Metrics> {
        let mut cres = super::agent::Metrics::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "GetMetrics", cres);
    }

    pub async fn create_sandbox(&self, ctx: ttrpc::context::Context, req: &super::agent::CreateSandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "CreateSandbox", cres);
    }

    pub async fn destroy_sandbox(&self, ctx: ttrpc::context::Context, req: &super::agent::DestroySandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "DestroySandbox", cres);
    }

    pub async fn online_cpu_mem(&self, ctx: ttrpc::context::Context, req: &super::agent::OnlineCPUMemRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "OnlineCPUMem", cres);
    }

    pub async fn reseed_random_dev(&self, ctx: ttrpc::context::Context, req: &super::agent::ReseedRandomDevRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ReseedRandomDev", cres);
    }

    pub async fn get_guest_details(&self, ctx: ttrpc::context::Context, req: &super::agent::GuestDetailsRequest) -> ::ttrpc::Result<super::agent::GuestDetailsResponse> {
        let mut cres = super::agent::GuestDetailsResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "GetGuestDetails", cres);
    }

    pub async fn mem_hotplug_by_probe(&self, ctx: ttrpc::context::Context, req: &super::agent::MemHotplugByProbeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "MemHotplugByProbe", cres);
    }

    pub async fn set_guest_date_time(&self, ctx: ttrpc::context::Context, req: &super::agent::SetGuestDateTimeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "SetGuestDateTime", cres);
    }

    pub async fn copy_file(&self, ctx: ttrpc::context::Context, req: &super::agent::CopyFileRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "CopyFile", cres);
    }

    pub async fn get_oom_event(&self, ctx: ttrpc::context::Context, req: &super::agent::GetOOMEventRequest) -> ::ttrpc::Result<super::agent::OOMEvent> {
        let mut cres = super::agent::OOMEvent::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "GetOOMEvent", cres);
    }

    pub async fn add_swap(&self, ctx: ttrpc::context::Context, req: &super::agent::AddSwapRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "AddSwap", cres);
    }

    pub async fn get_volume_stats(&self, ctx: ttrpc::context::Context, req: &super::agent::VolumeStatsRequest) -> ::ttrpc::Result<super::csi::VolumeStatsResponse> {
        let mut cres = super::csi::VolumeStatsResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "GetVolumeStats", cres);
    }

    pub async fn resize_volume(&self, ctx: ttrpc::context::Context, req: &super::agent::ResizeVolumeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.AgentService", "ResizeVolume", cres);
    }
}

struct CreateContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CreateContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, CreateContainerRequest, create_container);
    }
}

struct StartContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StartContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, StartContainerRequest, start_container);
    }
}

struct RemoveContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RemoveContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, RemoveContainerRequest, remove_container);
    }
}

struct ExecProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExecProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ExecProcessRequest, exec_process);
    }
}

struct SignalProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SignalProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, SignalProcessRequest, signal_process);
    }
}

struct WaitProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for WaitProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, WaitProcessRequest, wait_process);
    }
}

struct UpdateContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for UpdateContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, UpdateContainerRequest, update_container);
    }
}

struct UpdateEphemeralMountsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for UpdateEphemeralMountsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, UpdateEphemeralMountsRequest, update_ephemeral_mounts);
    }
}

struct StatsContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StatsContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, StatsContainerRequest, stats_container);
    }
}

struct PauseContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PauseContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, PauseContainerRequest, pause_container);
    }
}

struct ResumeContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ResumeContainerMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ResumeContainerRequest, resume_container);
    }
}

struct RemoveStaleVirtiofsShareMountsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RemoveStaleVirtiofsShareMountsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, RemoveStaleVirtiofsShareMountsRequest, remove_stale_virtiofs_share_mounts);
    }
}

struct WriteStdinMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for WriteStdinMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, WriteStreamRequest, write_stdin);
    }
}

struct ReadStdoutMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ReadStdoutMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ReadStreamRequest, read_stdout);
    }
}

struct ReadStderrMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ReadStderrMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ReadStreamRequest, read_stderr);
    }
}

struct CloseStdinMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CloseStdinMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, CloseStdinRequest, close_stdin);
    }
}

struct TtyWinResizeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for TtyWinResizeMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, TtyWinResizeRequest, tty_win_resize);
    }
}

struct UpdateInterfaceMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for UpdateInterfaceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, UpdateInterfaceRequest, update_interface);
    }
}

struct UpdateRoutesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for UpdateRoutesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, UpdateRoutesRequest, update_routes);
    }
}

struct ListInterfacesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ListInterfacesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ListInterfacesRequest, list_interfaces);
    }
}

struct ListRoutesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ListRoutesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ListRoutesRequest, list_routes);
    }
}

struct AddArpNeighborsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AddArpNeighborsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, AddARPNeighborsRequest, add_arp_neighbors);
    }
}

struct GetIpTablesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetIpTablesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, GetIPTablesRequest, get_ip_tables);
    }
}

struct SetIpTablesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SetIpTablesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, SetIPTablesRequest, set_ip_tables);
    }
}

struct GetMetricsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetMetricsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, GetMetricsRequest, get_metrics);
    }
}

struct CreateSandboxMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CreateSandboxMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, CreateSandboxRequest, create_sandbox);
    }
}

struct DestroySandboxMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for DestroySandboxMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, DestroySandboxRequest, destroy_sandbox);
    }
}

struct OnlineCpuMemMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OnlineCpuMemMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, OnlineCPUMemRequest, online_cpu_mem);
    }
}

struct ReseedRandomDevMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ReseedRandomDevMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ReseedRandomDevRequest, reseed_random_dev);
    }
}

struct GetGuestDetailsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetGuestDetailsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, GuestDetailsRequest, get_guest_details);
    }
}

struct MemHotplugByProbeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for MemHotplugByProbeMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, MemHotplugByProbeRequest, mem_hotplug_by_probe);
    }
}

struct SetGuestDateTimeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SetGuestDateTimeMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, SetGuestDateTimeRequest, set_guest_date_time);
    }
}

struct CopyFileMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CopyFileMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, CopyFileRequest, copy_file);
    }
}

struct GetOomEventMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetOomEventMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, GetOOMEventRequest, get_oom_event);
    }
}

struct AddSwapMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AddSwapMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, AddSwapRequest, add_swap);
    }
}

struct GetVolumeStatsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetVolumeStatsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, VolumeStatsRequest, get_volume_stats);
    }
}

struct ResizeVolumeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ResizeVolumeMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, agent, ResizeVolumeRequest, resize_volume);
    }
}

#[async_trait]
pub trait AgentService: Sync {
    async fn create_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::CreateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CreateContainer is not supported".to_string())))
    }
    async fn start_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::StartContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/StartContainer is not supported".to_string())))
    }
    async fn remove_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::RemoveContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/RemoveContainer is not supported".to_string())))
    }
    async fn exec_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ExecProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ExecProcess is not supported".to_string())))
    }
    async fn signal_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::SignalProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SignalProcess is not supported".to_string())))
    }
    async fn wait_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::WaitProcessRequest) -> ::ttrpc::Result<super::agent::WaitProcessResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/WaitProcess is not supported".to_string())))
    }
    async fn update_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::UpdateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateContainer is not supported".to_string())))
    }
    async fn update_ephemeral_mounts(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::UpdateEphemeralMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateEphemeralMounts is not supported".to_string())))
    }
    async fn stats_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::StatsContainerRequest) -> ::ttrpc::Result<super::agent::StatsContainerResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/StatsContainer is not supported".to_string())))
    }
    async fn pause_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::PauseContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/PauseContainer is not supported".to_string())))
    }
    async fn resume_container(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ResumeContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ResumeContainer is not supported".to_string())))
    }
    async fn remove_stale_virtiofs_share_mounts(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::RemoveStaleVirtiofsShareMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/RemoveStaleVirtiofsShareMounts is not supported".to_string())))
    }
    async fn write_stdin(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::WriteStreamRequest) -> ::ttrpc::Result<super::agent::WriteStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/WriteStdin is not supported".to_string())))
    }
    async fn read_stdout(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReadStdout is not supported".to_string())))
    }
    async fn read_stderr(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReadStderr is not supported".to_string())))
    }
    async fn close_stdin(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::CloseStdinRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CloseStdin is not supported".to_string())))
    }
    async fn tty_win_resize(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::TtyWinResizeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/TtyWinResize is not supported".to_string())))
    }
    async fn update_interface(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::UpdateInterfaceRequest) -> ::ttrpc::Result<super::types::Interface> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateInterface is not supported".to_string())))
    }
    async fn update_routes(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::UpdateRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateRoutes is not supported".to_string())))
    }
    async fn list_interfaces(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ListInterfacesRequest) -> ::ttrpc::Result<super::agent::Interfaces> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ListInterfaces is not supported".to_string())))
    }
    async fn list_routes(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ListRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ListRoutes is not supported".to_string())))
    }
    async fn add_arp_neighbors(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::AddARPNeighborsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/AddARPNeighbors is not supported".to_string())))
    }
    async fn get_ip_tables(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::GetIPTablesRequest) -> ::ttrpc::Result<super::agent::GetIPTablesResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetIPTables is not supported".to_string())))
    }
    async fn set_ip_tables(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::SetIPTablesRequest) -> ::ttrpc::Result<super::agent::SetIPTablesResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SetIPTables is not supported".to_string())))
    }
    async fn get_metrics(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::GetMetricsRequest) -> ::ttrpc::Result<super::agent::Metrics> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetMetrics is not supported".to_string())))
    }
    async fn create_sandbox(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::CreateSandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CreateSandbox is not supported".to_string())))
    }
    async fn destroy_sandbox(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::DestroySandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/DestroySandbox is not supported".to_string())))
    }
    async fn online_cpu_mem(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::OnlineCPUMemRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/OnlineCPUMem is not supported".to_string())))
    }
    async fn reseed_random_dev(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ReseedRandomDevRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReseedRandomDev is not supported".to_string())))
    }
    async fn get_guest_details(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::GuestDetailsRequest) -> ::ttrpc::Result<super::agent::GuestDetailsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetGuestDetails is not supported".to_string())))
    }
    async fn mem_hotplug_by_probe(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::MemHotplugByProbeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/MemHotplugByProbe is not supported".to_string())))
    }
    async fn set_guest_date_time(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::SetGuestDateTimeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SetGuestDateTime is not supported".to_string())))
    }
    async fn copy_file(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::CopyFileRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CopyFile is not supported".to_string())))
    }
    async fn get_oom_event(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::GetOOMEventRequest) -> ::ttrpc::Result<super::agent::OOMEvent> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetOOMEvent is not supported".to_string())))
    }
    async fn add_swap(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::AddSwapRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/AddSwap is not supported".to_string())))
    }
    async fn get_volume_stats(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::VolumeStatsRequest) -> ::ttrpc::Result<super::csi::VolumeStatsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetVolumeStats is not supported".to_string())))
    }
    async fn resize_volume(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::agent::ResizeVolumeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ResizeVolume is not supported".to_string())))
    }
}

pub fn create_agent_service(service: Arc<Box<dyn AgentService + Send + Sync>>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("CreateContainer".to_string(),
                    Box::new(CreateContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StartContainer".to_string(),
                    Box::new(StartContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RemoveContainer".to_string(),
                    Box::new(RemoveContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ExecProcess".to_string(),
                    Box::new(ExecProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("SignalProcess".to_string(),
                    Box::new(SignalProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("WaitProcess".to_string(),
                    Box::new(WaitProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("UpdateContainer".to_string(),
                    Box::new(UpdateContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("UpdateEphemeralMounts".to_string(),
                    Box::new(UpdateEphemeralMountsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StatsContainer".to_string(),
                    Box::new(StatsContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("PauseContainer".to_string(),
                    Box::new(PauseContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ResumeContainer".to_string(),
                    Box::new(ResumeContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RemoveStaleVirtiofsShareMounts".to_string(),
                    Box::new(RemoveStaleVirtiofsShareMountsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("WriteStdin".to_string(),
                    Box::new(WriteStdinMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ReadStdout".to_string(),
                    Box::new(ReadStdoutMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ReadStderr".to_string(),
                    Box::new(ReadStderrMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CloseStdin".to_string(),
                    Box::new(CloseStdinMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("TtyWinResize".to_string(),
                    Box::new(TtyWinResizeMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("UpdateInterface".to_string(),
                    Box::new(UpdateInterfaceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("UpdateRoutes".to_string(),
                    Box::new(UpdateRoutesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ListInterfaces".to_string(),
                    Box::new(ListInterfacesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ListRoutes".to_string(),
                    Box::new(ListRoutesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("AddARPNeighbors".to_string(),
                    Box::new(AddArpNeighborsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("GetIPTables".to_string(),
                    Box::new(GetIpTablesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("SetIPTables".to_string(),
                    Box::new(SetIpTablesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("GetMetrics".to_string(),
                    Box::new(GetMetricsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CreateSandbox".to_string(),
                    Box::new(CreateSandboxMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("DestroySandbox".to_string(),
                    Box::new(DestroySandboxMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("OnlineCPUMem".to_string(),
                    Box::new(OnlineCpuMemMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ReseedRandomDev".to_string(),
                    Box::new(ReseedRandomDevMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("GetGuestDetails".to_string(),
                    Box::new(GetGuestDetailsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("MemHotplugByProbe".to_string(),
                    Box::new(MemHotplugByProbeMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("SetGuestDateTime".to_string(),
                    Box::new(SetGuestDateTimeMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CopyFile".to_string(),
                    Box::new(CopyFileMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("GetOOMEvent".to_string(),
                    Box::new(GetOomEventMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("AddSwap".to_string(),
                    Box::new(AddSwapMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("GetVolumeStats".to_string(),
                    Box::new(GetVolumeStatsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ResizeVolume".to_string(),
                    Box::new(ResizeVolumeMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("grpc.AgentService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
