// This file is generated by ttrpc-compiler 0.6.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone)]
pub struct AgentServiceClient {
    client: ::ttrpc::Client,
}

impl AgentServiceClient {
    pub fn new(client: ::ttrpc::Client) -> Self {
        AgentServiceClient {
            client: client,
        }
    }

    pub fn create_container(&self, ctx: ttrpc::context::Context, req: &super::agent::CreateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "CreateContainer", cres);
        Ok(cres)
    }

    pub fn start_container(&self, ctx: ttrpc::context::Context, req: &super::agent::StartContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "StartContainer", cres);
        Ok(cres)
    }

    pub fn remove_container(&self, ctx: ttrpc::context::Context, req: &super::agent::RemoveContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "RemoveContainer", cres);
        Ok(cres)
    }

    pub fn exec_process(&self, ctx: ttrpc::context::Context, req: &super::agent::ExecProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ExecProcess", cres);
        Ok(cres)
    }

    pub fn signal_process(&self, ctx: ttrpc::context::Context, req: &super::agent::SignalProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "SignalProcess", cres);
        Ok(cres)
    }

    pub fn wait_process(&self, ctx: ttrpc::context::Context, req: &super::agent::WaitProcessRequest) -> ::ttrpc::Result<super::agent::WaitProcessResponse> {
        let mut cres = super::agent::WaitProcessResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "WaitProcess", cres);
        Ok(cres)
    }

    pub fn update_container(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "UpdateContainer", cres);
        Ok(cres)
    }

    pub fn update_ephemeral_mounts(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateEphemeralMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "UpdateEphemeralMounts", cres);
        Ok(cres)
    }

    pub fn stats_container(&self, ctx: ttrpc::context::Context, req: &super::agent::StatsContainerRequest) -> ::ttrpc::Result<super::agent::StatsContainerResponse> {
        let mut cres = super::agent::StatsContainerResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "StatsContainer", cres);
        Ok(cres)
    }

    pub fn pause_container(&self, ctx: ttrpc::context::Context, req: &super::agent::PauseContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "PauseContainer", cres);
        Ok(cres)
    }

    pub fn resume_container(&self, ctx: ttrpc::context::Context, req: &super::agent::ResumeContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ResumeContainer", cres);
        Ok(cres)
    }

    pub fn remove_stale_virtiofs_share_mounts(&self, ctx: ttrpc::context::Context, req: &super::agent::RemoveStaleVirtiofsShareMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "RemoveStaleVirtiofsShareMounts", cres);
        Ok(cres)
    }

    pub fn write_stdin(&self, ctx: ttrpc::context::Context, req: &super::agent::WriteStreamRequest) -> ::ttrpc::Result<super::agent::WriteStreamResponse> {
        let mut cres = super::agent::WriteStreamResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "WriteStdin", cres);
        Ok(cres)
    }

    pub fn read_stdout(&self, ctx: ttrpc::context::Context, req: &super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        let mut cres = super::agent::ReadStreamResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ReadStdout", cres);
        Ok(cres)
    }

    pub fn read_stderr(&self, ctx: ttrpc::context::Context, req: &super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        let mut cres = super::agent::ReadStreamResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ReadStderr", cres);
        Ok(cres)
    }

    pub fn close_stdin(&self, ctx: ttrpc::context::Context, req: &super::agent::CloseStdinRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "CloseStdin", cres);
        Ok(cres)
    }

    pub fn tty_win_resize(&self, ctx: ttrpc::context::Context, req: &super::agent::TtyWinResizeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "TtyWinResize", cres);
        Ok(cres)
    }

    pub fn update_interface(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateInterfaceRequest) -> ::ttrpc::Result<super::types::Interface> {
        let mut cres = super::types::Interface::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "UpdateInterface", cres);
        Ok(cres)
    }

    pub fn update_routes(&self, ctx: ttrpc::context::Context, req: &super::agent::UpdateRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        let mut cres = super::agent::Routes::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "UpdateRoutes", cres);
        Ok(cres)
    }

    pub fn list_interfaces(&self, ctx: ttrpc::context::Context, req: &super::agent::ListInterfacesRequest) -> ::ttrpc::Result<super::agent::Interfaces> {
        let mut cres = super::agent::Interfaces::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ListInterfaces", cres);
        Ok(cres)
    }

    pub fn list_routes(&self, ctx: ttrpc::context::Context, req: &super::agent::ListRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        let mut cres = super::agent::Routes::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ListRoutes", cres);
        Ok(cres)
    }

    pub fn add_arp_neighbors(&self, ctx: ttrpc::context::Context, req: &super::agent::AddARPNeighborsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "AddARPNeighbors", cres);
        Ok(cres)
    }

    pub fn get_ip_tables(&self, ctx: ttrpc::context::Context, req: &super::agent::GetIPTablesRequest) -> ::ttrpc::Result<super::agent::GetIPTablesResponse> {
        let mut cres = super::agent::GetIPTablesResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "GetIPTables", cres);
        Ok(cres)
    }

    pub fn set_ip_tables(&self, ctx: ttrpc::context::Context, req: &super::agent::SetIPTablesRequest) -> ::ttrpc::Result<super::agent::SetIPTablesResponse> {
        let mut cres = super::agent::SetIPTablesResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "SetIPTables", cres);
        Ok(cres)
    }

    pub fn get_metrics(&self, ctx: ttrpc::context::Context, req: &super::agent::GetMetricsRequest) -> ::ttrpc::Result<super::agent::Metrics> {
        let mut cres = super::agent::Metrics::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "GetMetrics", cres);
        Ok(cres)
    }

    pub fn create_sandbox(&self, ctx: ttrpc::context::Context, req: &super::agent::CreateSandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "CreateSandbox", cres);
        Ok(cres)
    }

    pub fn destroy_sandbox(&self, ctx: ttrpc::context::Context, req: &super::agent::DestroySandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "DestroySandbox", cres);
        Ok(cres)
    }

    pub fn online_cpu_mem(&self, ctx: ttrpc::context::Context, req: &super::agent::OnlineCPUMemRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "OnlineCPUMem", cres);
        Ok(cres)
    }

    pub fn reseed_random_dev(&self, ctx: ttrpc::context::Context, req: &super::agent::ReseedRandomDevRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ReseedRandomDev", cres);
        Ok(cres)
    }

    pub fn get_guest_details(&self, ctx: ttrpc::context::Context, req: &super::agent::GuestDetailsRequest) -> ::ttrpc::Result<super::agent::GuestDetailsResponse> {
        let mut cres = super::agent::GuestDetailsResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "GetGuestDetails", cres);
        Ok(cres)
    }

    pub fn mem_hotplug_by_probe(&self, ctx: ttrpc::context::Context, req: &super::agent::MemHotplugByProbeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "MemHotplugByProbe", cres);
        Ok(cres)
    }

    pub fn set_guest_date_time(&self, ctx: ttrpc::context::Context, req: &super::agent::SetGuestDateTimeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "SetGuestDateTime", cres);
        Ok(cres)
    }

    pub fn copy_file(&self, ctx: ttrpc::context::Context, req: &super::agent::CopyFileRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "CopyFile", cres);
        Ok(cres)
    }

    pub fn get_oom_event(&self, ctx: ttrpc::context::Context, req: &super::agent::GetOOMEventRequest) -> ::ttrpc::Result<super::agent::OOMEvent> {
        let mut cres = super::agent::OOMEvent::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "GetOOMEvent", cres);
        Ok(cres)
    }

    pub fn add_swap(&self, ctx: ttrpc::context::Context, req: &super::agent::AddSwapRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "AddSwap", cres);
        Ok(cres)
    }

    pub fn get_volume_stats(&self, ctx: ttrpc::context::Context, req: &super::agent::VolumeStatsRequest) -> ::ttrpc::Result<super::csi::VolumeStatsResponse> {
        let mut cres = super::csi::VolumeStatsResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "GetVolumeStats", cres);
        Ok(cres)
    }

    pub fn resize_volume(&self, ctx: ttrpc::context::Context, req: &super::agent::ResizeVolumeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "grpc.AgentService", "ResizeVolume", cres);
        Ok(cres)
    }
}

struct CreateContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for CreateContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, CreateContainerRequest, create_container);
        Ok(())
    }
}

struct StartContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for StartContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, StartContainerRequest, start_container);
        Ok(())
    }
}

struct RemoveContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for RemoveContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, RemoveContainerRequest, remove_container);
        Ok(())
    }
}

struct ExecProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ExecProcessMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ExecProcessRequest, exec_process);
        Ok(())
    }
}

struct SignalProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for SignalProcessMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, SignalProcessRequest, signal_process);
        Ok(())
    }
}

struct WaitProcessMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for WaitProcessMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, WaitProcessRequest, wait_process);
        Ok(())
    }
}

struct UpdateContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for UpdateContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, UpdateContainerRequest, update_container);
        Ok(())
    }
}

struct UpdateEphemeralMountsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for UpdateEphemeralMountsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, UpdateEphemeralMountsRequest, update_ephemeral_mounts);
        Ok(())
    }
}

struct StatsContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for StatsContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, StatsContainerRequest, stats_container);
        Ok(())
    }
}

struct PauseContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for PauseContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, PauseContainerRequest, pause_container);
        Ok(())
    }
}

struct ResumeContainerMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ResumeContainerMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ResumeContainerRequest, resume_container);
        Ok(())
    }
}

struct RemoveStaleVirtiofsShareMountsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for RemoveStaleVirtiofsShareMountsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, RemoveStaleVirtiofsShareMountsRequest, remove_stale_virtiofs_share_mounts);
        Ok(())
    }
}

struct WriteStdinMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for WriteStdinMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, WriteStreamRequest, write_stdin);
        Ok(())
    }
}

struct ReadStdoutMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ReadStdoutMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ReadStreamRequest, read_stdout);
        Ok(())
    }
}

struct ReadStderrMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ReadStderrMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ReadStreamRequest, read_stderr);
        Ok(())
    }
}

struct CloseStdinMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for CloseStdinMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, CloseStdinRequest, close_stdin);
        Ok(())
    }
}

struct TtyWinResizeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for TtyWinResizeMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, TtyWinResizeRequest, tty_win_resize);
        Ok(())
    }
}

struct UpdateInterfaceMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for UpdateInterfaceMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, UpdateInterfaceRequest, update_interface);
        Ok(())
    }
}

struct UpdateRoutesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for UpdateRoutesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, UpdateRoutesRequest, update_routes);
        Ok(())
    }
}

struct ListInterfacesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ListInterfacesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ListInterfacesRequest, list_interfaces);
        Ok(())
    }
}

struct ListRoutesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ListRoutesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ListRoutesRequest, list_routes);
        Ok(())
    }
}

struct AddArpNeighborsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for AddArpNeighborsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, AddARPNeighborsRequest, add_arp_neighbors);
        Ok(())
    }
}

struct GetIpTablesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetIpTablesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, GetIPTablesRequest, get_ip_tables);
        Ok(())
    }
}

struct SetIpTablesMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for SetIpTablesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, SetIPTablesRequest, set_ip_tables);
        Ok(())
    }
}

struct GetMetricsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetMetricsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, GetMetricsRequest, get_metrics);
        Ok(())
    }
}

struct CreateSandboxMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for CreateSandboxMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, CreateSandboxRequest, create_sandbox);
        Ok(())
    }
}

struct DestroySandboxMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for DestroySandboxMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, DestroySandboxRequest, destroy_sandbox);
        Ok(())
    }
}

struct OnlineCpuMemMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for OnlineCpuMemMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, OnlineCPUMemRequest, online_cpu_mem);
        Ok(())
    }
}

struct ReseedRandomDevMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ReseedRandomDevMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ReseedRandomDevRequest, reseed_random_dev);
        Ok(())
    }
}

struct GetGuestDetailsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetGuestDetailsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, GuestDetailsRequest, get_guest_details);
        Ok(())
    }
}

struct MemHotplugByProbeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for MemHotplugByProbeMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, MemHotplugByProbeRequest, mem_hotplug_by_probe);
        Ok(())
    }
}

struct SetGuestDateTimeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for SetGuestDateTimeMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, SetGuestDateTimeRequest, set_guest_date_time);
        Ok(())
    }
}

struct CopyFileMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for CopyFileMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, CopyFileRequest, copy_file);
        Ok(())
    }
}

struct GetOomEventMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetOomEventMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, GetOOMEventRequest, get_oom_event);
        Ok(())
    }
}

struct AddSwapMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for AddSwapMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, AddSwapRequest, add_swap);
        Ok(())
    }
}

struct GetVolumeStatsMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetVolumeStatsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, VolumeStatsRequest, get_volume_stats);
        Ok(())
    }
}

struct ResizeVolumeMethod {
    service: Arc<Box<dyn AgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for ResizeVolumeMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, agent, ResizeVolumeRequest, resize_volume);
        Ok(())
    }
}

pub trait AgentService {
    fn create_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::CreateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CreateContainer is not supported".to_string())))
    }
    fn start_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::StartContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/StartContainer is not supported".to_string())))
    }
    fn remove_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::RemoveContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/RemoveContainer is not supported".to_string())))
    }
    fn exec_process(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ExecProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ExecProcess is not supported".to_string())))
    }
    fn signal_process(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::SignalProcessRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SignalProcess is not supported".to_string())))
    }
    fn wait_process(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::WaitProcessRequest) -> ::ttrpc::Result<super::agent::WaitProcessResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/WaitProcess is not supported".to_string())))
    }
    fn update_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::UpdateContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateContainer is not supported".to_string())))
    }
    fn update_ephemeral_mounts(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::UpdateEphemeralMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateEphemeralMounts is not supported".to_string())))
    }
    fn stats_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::StatsContainerRequest) -> ::ttrpc::Result<super::agent::StatsContainerResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/StatsContainer is not supported".to_string())))
    }
    fn pause_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::PauseContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/PauseContainer is not supported".to_string())))
    }
    fn resume_container(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ResumeContainerRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ResumeContainer is not supported".to_string())))
    }
    fn remove_stale_virtiofs_share_mounts(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::RemoveStaleVirtiofsShareMountsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/RemoveStaleVirtiofsShareMounts is not supported".to_string())))
    }
    fn write_stdin(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::WriteStreamRequest) -> ::ttrpc::Result<super::agent::WriteStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/WriteStdin is not supported".to_string())))
    }
    fn read_stdout(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReadStdout is not supported".to_string())))
    }
    fn read_stderr(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ReadStreamRequest) -> ::ttrpc::Result<super::agent::ReadStreamResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReadStderr is not supported".to_string())))
    }
    fn close_stdin(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::CloseStdinRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CloseStdin is not supported".to_string())))
    }
    fn tty_win_resize(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::TtyWinResizeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/TtyWinResize is not supported".to_string())))
    }
    fn update_interface(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::UpdateInterfaceRequest) -> ::ttrpc::Result<super::types::Interface> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateInterface is not supported".to_string())))
    }
    fn update_routes(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::UpdateRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/UpdateRoutes is not supported".to_string())))
    }
    fn list_interfaces(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ListInterfacesRequest) -> ::ttrpc::Result<super::agent::Interfaces> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ListInterfaces is not supported".to_string())))
    }
    fn list_routes(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ListRoutesRequest) -> ::ttrpc::Result<super::agent::Routes> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ListRoutes is not supported".to_string())))
    }
    fn add_arp_neighbors(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::AddARPNeighborsRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/AddARPNeighbors is not supported".to_string())))
    }
    fn get_ip_tables(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::GetIPTablesRequest) -> ::ttrpc::Result<super::agent::GetIPTablesResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetIPTables is not supported".to_string())))
    }
    fn set_ip_tables(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::SetIPTablesRequest) -> ::ttrpc::Result<super::agent::SetIPTablesResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SetIPTables is not supported".to_string())))
    }
    fn get_metrics(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::GetMetricsRequest) -> ::ttrpc::Result<super::agent::Metrics> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetMetrics is not supported".to_string())))
    }
    fn create_sandbox(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::CreateSandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CreateSandbox is not supported".to_string())))
    }
    fn destroy_sandbox(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::DestroySandboxRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/DestroySandbox is not supported".to_string())))
    }
    fn online_cpu_mem(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::OnlineCPUMemRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/OnlineCPUMem is not supported".to_string())))
    }
    fn reseed_random_dev(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ReseedRandomDevRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ReseedRandomDev is not supported".to_string())))
    }
    fn get_guest_details(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::GuestDetailsRequest) -> ::ttrpc::Result<super::agent::GuestDetailsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetGuestDetails is not supported".to_string())))
    }
    fn mem_hotplug_by_probe(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::MemHotplugByProbeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/MemHotplugByProbe is not supported".to_string())))
    }
    fn set_guest_date_time(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::SetGuestDateTimeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/SetGuestDateTime is not supported".to_string())))
    }
    fn copy_file(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::CopyFileRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/CopyFile is not supported".to_string())))
    }
    fn get_oom_event(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::GetOOMEventRequest) -> ::ttrpc::Result<super::agent::OOMEvent> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetOOMEvent is not supported".to_string())))
    }
    fn add_swap(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::AddSwapRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/AddSwap is not supported".to_string())))
    }
    fn get_volume_stats(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::VolumeStatsRequest) -> ::ttrpc::Result<super::csi::VolumeStatsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/GetVolumeStats is not supported".to_string())))
    }
    fn resize_volume(&self, _ctx: &::ttrpc::TtrpcContext, _: super::agent::ResizeVolumeRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.AgentService/ResizeVolume is not supported".to_string())))
    }
}

pub fn create_agent_service(service: Arc<Box<dyn AgentService + Send + Sync>>) -> HashMap<String, Box<dyn ::ttrpc::MethodHandler + Send + Sync>> {
    let mut methods = HashMap::new();

    methods.insert("/grpc.AgentService/CreateContainer".to_string(),
                    Box::new(CreateContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/StartContainer".to_string(),
                    Box::new(StartContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/RemoveContainer".to_string(),
                    Box::new(RemoveContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ExecProcess".to_string(),
                    Box::new(ExecProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/SignalProcess".to_string(),
                    Box::new(SignalProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/WaitProcess".to_string(),
                    Box::new(WaitProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/UpdateContainer".to_string(),
                    Box::new(UpdateContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/UpdateEphemeralMounts".to_string(),
                    Box::new(UpdateEphemeralMountsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/StatsContainer".to_string(),
                    Box::new(StatsContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/PauseContainer".to_string(),
                    Box::new(PauseContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ResumeContainer".to_string(),
                    Box::new(ResumeContainerMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/RemoveStaleVirtiofsShareMounts".to_string(),
                    Box::new(RemoveStaleVirtiofsShareMountsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/WriteStdin".to_string(),
                    Box::new(WriteStdinMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ReadStdout".to_string(),
                    Box::new(ReadStdoutMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ReadStderr".to_string(),
                    Box::new(ReadStderrMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/CloseStdin".to_string(),
                    Box::new(CloseStdinMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/TtyWinResize".to_string(),
                    Box::new(TtyWinResizeMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/UpdateInterface".to_string(),
                    Box::new(UpdateInterfaceMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/UpdateRoutes".to_string(),
                    Box::new(UpdateRoutesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ListInterfaces".to_string(),
                    Box::new(ListInterfacesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ListRoutes".to_string(),
                    Box::new(ListRoutesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/AddARPNeighbors".to_string(),
                    Box::new(AddArpNeighborsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/GetIPTables".to_string(),
                    Box::new(GetIpTablesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/SetIPTables".to_string(),
                    Box::new(SetIpTablesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/GetMetrics".to_string(),
                    Box::new(GetMetricsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/CreateSandbox".to_string(),
                    Box::new(CreateSandboxMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/DestroySandbox".to_string(),
                    Box::new(DestroySandboxMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/OnlineCPUMem".to_string(),
                    Box::new(OnlineCpuMemMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ReseedRandomDev".to_string(),
                    Box::new(ReseedRandomDevMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/GetGuestDetails".to_string(),
                    Box::new(GetGuestDetailsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/MemHotplugByProbe".to_string(),
                    Box::new(MemHotplugByProbeMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/SetGuestDateTime".to_string(),
                    Box::new(SetGuestDateTimeMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/CopyFile".to_string(),
                    Box::new(CopyFileMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/GetOOMEvent".to_string(),
                    Box::new(GetOomEventMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/AddSwap".to_string(),
                    Box::new(AddSwapMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/GetVolumeStats".to_string(),
                    Box::new(GetVolumeStatsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/grpc.AgentService/ResizeVolume".to_string(),
                    Box::new(ResizeVolumeMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods
}
