// This file is generated by ttrpc-compiler 0.6.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct HealthClient {
    client: ::ttrpc::r#async::Client,
}

impl HealthClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        HealthClient {
            client: client,
        }
    }

    pub async fn check(&self, ctx: ttrpc::context::Context, req: &super::health::CheckRequest) -> ::ttrpc::Result<super::health::HealthCheckResponse> {
        let mut cres = super::health::HealthCheckResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.Health", "Check", cres);
    }

    pub async fn version(&self, ctx: ttrpc::context::Context, req: &super::health::CheckRequest) -> ::ttrpc::Result<super::health::VersionCheckResponse> {
        let mut cres = super::health::VersionCheckResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "grpc.Health", "Version", cres);
    }
}

struct CheckMethod {
    service: Arc<Box<dyn Health + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CheckMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, health, CheckRequest, check);
    }
}

struct VersionMethod {
    service: Arc<Box<dyn Health + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for VersionMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, health, CheckRequest, version);
    }
}

#[async_trait]
pub trait Health: Sync {
    async fn check(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::health::CheckRequest) -> ::ttrpc::Result<super::health::HealthCheckResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.Health/Check is not supported".to_string())))
    }
    async fn version(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::health::CheckRequest) -> ::ttrpc::Result<super::health::VersionCheckResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/grpc.Health/Version is not supported".to_string())))
    }
}

pub fn create_health(service: Arc<Box<dyn Health + Send + Sync>>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Check".to_string(),
                    Box::new(CheckMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Version".to_string(),
                    Box::new(VersionMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("grpc.Health".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
